include(FetchContent)
# Fetches a github repo by the git tag and adds it as a dependency
macro(add_github_dependency_by_tag name project_name tag)
    if (NOT "${ARGN}" STREQUAL "")
        message(SEND_ERROR "add_github_dependency takes only a three argument.  Offending args: ${ARGN}")
    endif()    
    set(full_url "https://github.com/${project_name}.git") 
    FetchContent_Declare(${name} GIT_REPOSITORY ${full_url} GIT_TAG ${tag})
    FetchContent_MakeAvailable(${name})
endmacro()

macro(add_github_dependency name project_name)
    if (NOT "${ARGN}" STREQUAL "")
        message(SEND_ERROR "add_github_dependency takes only a two argument.  Offending args: ${ARGN}")
    endif()    
    set(full_url "https://github.com/${project_name}.git")
    FetchContent_Declare(${name} GIT_REPOSITORY ${full_url})
    FetchContent_MakeAvailable(${name})
endmacro()

macro(add_svn_dependency name url)
    if (NOT "${ARGN}" STREQUAL "")
        message(SEND_ERROR "add_svn_dependency takes only a two argument.  Offending args: ${ARGN}")
    endif()    
    FetchContent_Declare(${name} SVN_REPOSITORY ${url})
    FetchContent_MakeAvailable(${name})
endmacro()